jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Fetch Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./ci/check

name: Run

on:
  schedule:
    - cron: "15 1/3 * * *"
